name: run-tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ["5.6"]

    name: P-${{ matrix.php}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

#on: push
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: true
#      matrix:
#        php: [ "5.6" ]
#        laravel: [ "5.2.*" ]
#        phpunit: [ "~5.0" ]
#        testbench: [ "3.2.*" ]

#    name: PHP${{ matrix.php }} - LARAVEL${{ matrix.laravel }} - PHPUNIT${{ matrix.phpunit}} - TESTBENCH${{ matrix.testbench }}

#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2

#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: ${{ matrix.php }}
#
#      - name: Composer dependencies
#        run: |
#          composer require "illuminate/contracts:${{ matrix.laravel }}" "phpunit/phpunit:${{ matrix.phpunit }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
#
#      - name: Tests
#        run: vendor/bin/phpunit
