name: run-tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - php: 5.6
            laravel: 5.2.*
            phpunit: ~5.0
            testbench: 3.2.*
          - php: 5.6
            laravel: 5.3.*
            phpunit: ~5.0
            testbench: 3.3.*
          - php: 5.6
            laravel: 5.4.*
            phpunit: ~5.7
            testbench: 3.4.*
          - php: 7.0
            laravel: 5.2.*
            phpunit: ~5.0
            testbench: 3.2.*
          - php: 7.0
            laravel: 5.3.*
            phpunit: ~5.0
            testbench: 3.3.*
          - php: 7.0
            laravel: 5.4.*
            phpunit: ~5.7
            testbench: 3.4.*
          - php: 7.0
            laravel: 5.5.*
            phpunit: ~6.0
            testbench: 3.5.*
          - php: 7.1
            laravel: 5.2.*
            phpunit: ~5.0
            testbench: 3.2.*
          - php: 7.1
            laravel: 5.3.*
            phpunit: ~5.0
            testbench: 3.3.*
          - php: 7.1
            laravel: 5.4.*
            phpunit: ~5.7
            testbench: 3.4.*
          - php: 7.1
            laravel: 5.5.*
            phpunit: ~6.0
            testbench: 3.5.*
          - php: 7.1
            laravel: 5.6.*
            phpunit: ^7.0
            testbench: 3.6.*
          - php: 7.1
            laravel: 5.7.*
            phpunit: ^7.0
            testbench: 3.7.*
          - php: 7.1
            laravel: 5.8.*
            phpunit: ^7.0
            testbench: 3.8.*
          - php: 7.2
            laravel: 5.4.*
            phpunit: ~5.7
            testbench: 3.4.*
          - php: 7.2
            laravel: 5.5.*
            phpunit: ~6.0
            testbench: 3.5.*
          - php: 7.2
            laravel: 5.6.*
            phpunit: ^7.0
            testbench: 3.6.*
          - php: 7.2
            laravel: 5.7.*
            phpunit: ^7.0
            testbench: 3.7.*
          - php: 7.2
            laravel: 5.8.*
            phpunit: ^7.0
            testbench: 3.8.*
          - php: 7.2
            laravel: 6.*
            phpunit: ^8.4
            testbench: 4.*
          - php: 7.2
            laravel: 7.*
            phpunit: ^8.4
            testbench: 5.*
          - php: 7.3
            laravel: 5.7.*
            phpunit: ^7.0
            testbench: 3.7.*
          - php: 7.3
            laravel: 5.8.*
            phpunit: ^7.0
            testbench: 3.8.*
          - php: 7.3
            laravel: 6.*
            phpunit: ^8.4
            testbench: 4.*
          - php: 7.3
            laravel: 7.*
            phpunit: ^8.4
            testbench: 5.*
          - php: 7.3
            laravel: 8.*
            phpunit: ^9.0
            testbench: 6.*
          - php: 7.4
            laravel: 5.8.*
            phpunit: ^7.0
            testbench: 3.8.*
          - php: 7.4
            laravel: 6.*
            phpunit: ^8.4
            testbench: 4.*
          - php: 7.4
            laravel: 7.*
            phpunit: ^8.4
            testbench: 5.*
          - php: 7.4
            laravel: 8.*
            phpunit: ^9.0
            testbench: 6.*
          - php: 8.0
            laravel: 9.*
            phpunit: ^9.0
            testbench: 7.*
          - php: 8.1
            laravel: 9.*
            phpunit: ^9.0
            testbench: 7.*

    name: PHP-${{ matrix.php}}-LARAVEL-${{ matrix.laravel }}-PHPUNIT-${{ matrix.phpunit }}-TESTBENCH-${{ matrix.testbench }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Composer dependencies
        run: |
          composer require "illuminate/contracts:${{ matrix.laravel }}" "phpunit/phpunit:${{ matrix.phpunit }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer install --prefer-dist --no-interaction --no-suggest

      - name: Tests
        run: vendor/bin/phpunit
